[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["ohmmaagoch <ohm@42bangkok.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.7.0"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
